// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(PersonnelManagementContext))]
    [Migration("20250605141142_SeedInitDate")]
    partial class SeedInitDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RegistryName")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");
                });

            modelBuilder.Entity("Entities.Concrete.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adıyaman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ağrı"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amasya"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Artvin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Aydın"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Balıkesir"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bilecik"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bingöl"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bitlis"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bolu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Burdur"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Çanakkale"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Çankırı"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Çorum"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Denizli"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Diyarbakır"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Edirne"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Elazığ"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Erzincan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Erzurum"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Gaziantep"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Giresun"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Gümüşhane"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hakkâri"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hatay"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Isparta"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Mersin"
                        },
                        new
                        {
                            Id = 34,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 35,
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Kars"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Kastamonu"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Kayseri"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Kırklareli"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Kırşehir"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Kocaeli"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Konya"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Kütahya"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Malatya"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Manisa"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Mardin"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Muğla"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Muş"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Nevşehir"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Niğde"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ordu"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Rize"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Samsun"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Siirt"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Sinop"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Sivas"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Tekirdağ"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Tokat"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Trabzon"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Tunceli"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Şanlıurfa"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Uşak"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Van"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Yozgat"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Zonguldak"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Aksaray"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Bayburt"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Karaman"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Kırıkkale"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Batman"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Şırnak"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Bartın"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ardahan"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iğdır"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Yalova"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Karabük"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Kilis"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Osmaniye"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Düzce"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Courthouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Courthouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Adana Adliyesi"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Adıyaman Adliyesi"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Afyonkarahisar Adliyesi"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Ağrı Adliyesi"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Name = "Amasya Adliyesi"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Name = "Ankara Adliyesi"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Name = "Antalya Adliyesi"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            Name = "Artvin Adliyesi"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 9,
                            Name = "Aydın Adliyesi"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 10,
                            Name = "Balıkesir Adliyesi"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            Name = "Bilecik Adliyesi"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 12,
                            Name = "Bingöl Adliyesi"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 13,
                            Name = "Bitlis Adliyesi"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 14,
                            Name = "Bolu Adliyesi"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 15,
                            Name = "Burdur Adliyesi"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 16,
                            Name = "Bursa Adliyesi"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 17,
                            Name = "Çanakkale Adliyesi"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 18,
                            Name = "Çankırı Adliyesi"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 19,
                            Name = "Çorum Adliyesi"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 20,
                            Name = "Denizli Adliyesi"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 21,
                            Name = "Diyarbakır Adliyesi"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 22,
                            Name = "Edirne Adliyesi"
                        },
                        new
                        {
                            Id = 23,
                            CityId = 23,
                            Name = "Elazığ Adliyesi"
                        },
                        new
                        {
                            Id = 24,
                            CityId = 24,
                            Name = "Erzincan Adliyesi"
                        },
                        new
                        {
                            Id = 25,
                            CityId = 25,
                            Name = "Erzurum Adliyesi"
                        },
                        new
                        {
                            Id = 26,
                            CityId = 26,
                            Name = "Eskişehir Adliyesi"
                        },
                        new
                        {
                            Id = 27,
                            CityId = 27,
                            Name = "Gaziantep Adliyesi"
                        },
                        new
                        {
                            Id = 28,
                            CityId = 28,
                            Name = "Giresun Adliyesi"
                        },
                        new
                        {
                            Id = 29,
                            CityId = 29,
                            Name = "Gümüşhane Adliyesi"
                        },
                        new
                        {
                            Id = 30,
                            CityId = 30,
                            Name = "Hakkâri Adliyesi"
                        },
                        new
                        {
                            Id = 31,
                            CityId = 31,
                            Name = "Hatay Adliyesi"
                        },
                        new
                        {
                            Id = 32,
                            CityId = 32,
                            Name = "Isparta Adliyesi"
                        },
                        new
                        {
                            Id = 33,
                            CityId = 33,
                            Name = "Mersin Adliyesi"
                        },
                        new
                        {
                            Id = 34,
                            CityId = 34,
                            Name = "İstanbul Adliyesi"
                        },
                        new
                        {
                            Id = 35,
                            CityId = 35,
                            Name = "İzmir Adliyesi"
                        },
                        new
                        {
                            Id = 36,
                            CityId = 36,
                            Name = "Kars Adliyesi"
                        },
                        new
                        {
                            Id = 37,
                            CityId = 37,
                            Name = "Kastamonu Adliyesi"
                        },
                        new
                        {
                            Id = 38,
                            CityId = 38,
                            Name = "Kayseri Adliyesi"
                        },
                        new
                        {
                            Id = 39,
                            CityId = 39,
                            Name = "Kırklareli Adliyesi"
                        },
                        new
                        {
                            Id = 40,
                            CityId = 40,
                            Name = "Kırşehir Adliyesi"
                        },
                        new
                        {
                            Id = 41,
                            CityId = 41,
                            Name = "Kocaeli Adliyesi"
                        },
                        new
                        {
                            Id = 42,
                            CityId = 42,
                            Name = "Konya Adliyesi"
                        },
                        new
                        {
                            Id = 43,
                            CityId = 43,
                            Name = "Kütahya Adliyesi"
                        },
                        new
                        {
                            Id = 44,
                            CityId = 44,
                            Name = "Malatya Adliyesi"
                        },
                        new
                        {
                            Id = 45,
                            CityId = 45,
                            Name = "Manisa Adliyesi"
                        },
                        new
                        {
                            Id = 46,
                            CityId = 46,
                            Name = "Kahramanmaraş Adliyesi"
                        },
                        new
                        {
                            Id = 47,
                            CityId = 47,
                            Name = "Mardin Adliyesi"
                        },
                        new
                        {
                            Id = 48,
                            CityId = 48,
                            Name = "Muğla Adliyesi"
                        },
                        new
                        {
                            Id = 49,
                            CityId = 49,
                            Name = "Muş Adliyesi"
                        },
                        new
                        {
                            Id = 50,
                            CityId = 50,
                            Name = "Nevşehir Adliyesi"
                        },
                        new
                        {
                            Id = 51,
                            CityId = 51,
                            Name = "Niğde Adliyesi"
                        },
                        new
                        {
                            Id = 52,
                            CityId = 52,
                            Name = "Ordu Adliyesi"
                        },
                        new
                        {
                            Id = 53,
                            CityId = 53,
                            Name = "Rize Adliyesi"
                        },
                        new
                        {
                            Id = 54,
                            CityId = 54,
                            Name = "Sakarya Adliyesi"
                        },
                        new
                        {
                            Id = 55,
                            CityId = 55,
                            Name = "Samsun Adliyesi"
                        },
                        new
                        {
                            Id = 56,
                            CityId = 56,
                            Name = "Siirt Adliyesi"
                        },
                        new
                        {
                            Id = 57,
                            CityId = 57,
                            Name = "Sinop Adliyesi"
                        },
                        new
                        {
                            Id = 58,
                            CityId = 58,
                            Name = "Sivas Adliyesi"
                        },
                        new
                        {
                            Id = 59,
                            CityId = 59,
                            Name = "Tekirdağ Adliyesi"
                        },
                        new
                        {
                            Id = 60,
                            CityId = 60,
                            Name = "Tokat Adliyesi"
                        },
                        new
                        {
                            Id = 61,
                            CityId = 61,
                            Name = "Trabzon Adliyesi"
                        },
                        new
                        {
                            Id = 62,
                            CityId = 62,
                            Name = "Tunceli Adliyesi"
                        },
                        new
                        {
                            Id = 63,
                            CityId = 63,
                            Name = "Şanlıurfa Adliyesi"
                        },
                        new
                        {
                            Id = 64,
                            CityId = 64,
                            Name = "Uşak Adliyesi"
                        },
                        new
                        {
                            Id = 65,
                            CityId = 65,
                            Name = "Van Adliyesi"
                        },
                        new
                        {
                            Id = 66,
                            CityId = 66,
                            Name = "Yozgat Adliyesi"
                        },
                        new
                        {
                            Id = 67,
                            CityId = 67,
                            Name = "Zonguldak Adliyesi"
                        },
                        new
                        {
                            Id = 68,
                            CityId = 68,
                            Name = "Aksaray Adliyesi"
                        },
                        new
                        {
                            Id = 69,
                            CityId = 69,
                            Name = "Bayburt Adliyesi"
                        },
                        new
                        {
                            Id = 70,
                            CityId = 70,
                            Name = "Karaman Adliyesi"
                        },
                        new
                        {
                            Id = 71,
                            CityId = 71,
                            Name = "Kırıkkale Adliyesi"
                        },
                        new
                        {
                            Id = 72,
                            CityId = 72,
                            Name = "Batman Adliyesi"
                        },
                        new
                        {
                            Id = 73,
                            CityId = 73,
                            Name = "Şırnak Adliyesi"
                        },
                        new
                        {
                            Id = 74,
                            CityId = 74,
                            Name = "Bartın Adliyesi"
                        },
                        new
                        {
                            Id = 75,
                            CityId = 75,
                            Name = "Ardahan Adliyesi"
                        },
                        new
                        {
                            Id = 76,
                            CityId = 76,
                            Name = "Iğdır Adliyesi"
                        },
                        new
                        {
                            Id = 77,
                            CityId = 77,
                            Name = "Yalova Adliyesi"
                        },
                        new
                        {
                            Id = 78,
                            CityId = 78,
                            Name = "Karabük Adliyesi"
                        },
                        new
                        {
                            Id = 79,
                            CityId = 79,
                            Name = "Kilis Adliyesi"
                        },
                        new
                        {
                            Id = 80,
                            CityId = 80,
                            Name = "Osmaniye Adliyesi"
                        },
                        new
                        {
                            Id = 81,
                            CityId = 81,
                            Name = "Düzce Adliyesi"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.TransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationCourthouseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransferTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UsertId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCourthouseId");

                    b.HasIndex("TransferTypeId");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("Entities.Concrete.TransferType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransferTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eş Durum"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tayin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mazeret"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Courthouse", b =>
                {
                    b.HasOne("Entities.Concrete.City", "City")
                        .WithMany("Courthouses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Entities.Concrete.TransferRequest", b =>
                {
                    b.HasOne("Entities.Concrete.Courthouse", "DestinationCourthouse")
                        .WithMany("transferRequests")
                        .HasForeignKey("DestinationCourthouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.TransferType", "TransferType")
                        .WithMany("TransferRequests")
                        .HasForeignKey("TransferTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationCourthouse");

                    b.Navigation("TransferType");
                });

            modelBuilder.Entity("Entities.Concrete.City", b =>
                {
                    b.Navigation("Courthouses");
                });

            modelBuilder.Entity("Entities.Concrete.Courthouse", b =>
                {
                    b.Navigation("transferRequests");
                });

            modelBuilder.Entity("Entities.Concrete.TransferType", b =>
                {
                    b.Navigation("TransferRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
